package de.htwg.se.Roulette.model

import org.scalatest.wordspec.AnyWordSpec
import org.scalatest.matchers.should.Matchers

class PrintBoxRowSpec extends AnyWordSpec with Matchers {

  "PrintBoxRow.printBoxRow" when {

    "creating a simple row with includeBottom = true" should {
      "render the correct ASCII box structure and include the bottom line" in {
        val totalWidth = 10
        val boxHeight = 3
        val boxesPerRow = 2
        val result = PrintBoxRow.printBoxRow(
          totalWidth = totalWidth,
          boxHeight = boxHeight,
          boxesPerRow = boxesPerRow,
          includeBottom = true,
          rowIndex = 1,
        )

        val lines = result.split("\n").toList

        // top
        lines.head shouldBe "+-----+-----+"

        // there should be 1 (top) + boxHeight + 1 (bottom)
        lines.length shouldBe (1 + boxHeight + 1)

        // should contain numbers 1 and 2 and be bounded by |
        val numberLine = lines(1 + (boxHeight / 2))
        numberLine should startWith("|")
        numberLine should endWith("|")
        numberLine should include("1")
        numberLine should include("2")

        // should match PrintLine.printLine
        lines.last shouldBe PrintLine.printLine(totalWidth, boxesPerRow)
      }
    }

    "creating a simple row with includeBottom = false" should {
      "render the correct ASCII box structure and omit the bottom line" in {
        val totalWidth = 10
        val boxHeight = 3
        val boxesPerRow = 2
        val result = PrintBoxRow.printBoxRow(
          totalWidth = totalWidth,
          boxHeight = boxHeight,
          boxesPerRow = boxesPerRow,
          includeBottom = false,
          rowIndex = 1,
          offset = 0
        )

        val lines = result.split("\n").toList

        // top border
        lines.head shouldBe "+-----+-----+"

        // should be 1 (top) + boxHeight lines without bottom
        lines.length shouldBe (1 + boxHeight)

        // bottom line =/= PrintLine.printLine
        lines.last should not equal PrintLine.printLine(totalWidth, boxesPerRow)
      }
    }

    "offset is applied" should {
      "prepend spaces correctly to every printed line" in {
        val result = PrintBoxRow.printBoxRow(
          totalWidth = 6,
          boxHeight = 1,
          boxesPerRow = 1,
          includeBottom = false,
          rowIndex = 1,
          offset = 3
        )

        val lines = result.split("\n").toList
        lines.foreach { line =>
          line should startWith("   ") // 3 spaces
        }
      }
    }

    "numbers are generated by row index" should {
      "start numbering correctly for rowIndex = 2" in {
        val totalWidth = 10
        val boxHeight = 3
        val boxesPerRow = 2
        val result = PrintBoxRow.printBoxRow(
          totalWidth = totalWidth,
          boxHeight = boxHeight,
          boxesPerRow = boxesPerRow,
          includeBottom = false,
          rowIndex = 2,
        )

        val lines = result.split("\n").toList
        val numberLine = lines(1 + (boxHeight / 2))

        // rowIndex = 2 -> startNum = (boxesPerRow * (2 - 1)) + 1 = 3
        numberLine should include("3")
        numberLine should include("4")
      }
    }
  }
}
