package de.htwg.se.Roulette.model

import java.lang.reflect.Field
import org.scalatest.wordspec.AnyWordSpec
import org.scalatest.matchers.should.Matchers

class TableBuilderSpec extends AnyWordSpec with Matchers {

  "A TableBuilder" should {
    val totalWidth = 12
    val height = 3
    val builder = new TableBuilder(totalWidth, height, Some(5))

    // Helper to access private fields for testing
    def getPrivateField[T](obj: AnyRef, fieldName: String): T = {
      val field: Field = obj.getClass.getDeclaredField(fieldName)
      field.setAccessible(true)
      field.get(obj).asInstanceOf[T]
    }

    "build the hex part" in {
      val newBuilder = new TableBuilder(totalWidth, height, Some(5)).buildHexPart()
      val result = getPrivateField[String](newBuilder, "hexBlock")
      result should include("/")
      result should include("\\")
      result should include("5")
    }

    "build the table grid part" in {
      val newBuilder = new TableBuilder(totalWidth, height, Some(5)).buildTableGridPart()
      val result = getPrivateField[String](newBuilder, "tableBlock")
      result should include("+----+----+----+")
      result should include("R")
      result should include("B")
    }

    "build the side parts" in {
      val newBuilder = new TableBuilder(totalWidth, height, Some(5)).buildSideParts()
      val sideResult = getPrivateField[String](newBuilder, "sideBlock")
      val thirdsResult = getPrivateField[String](newBuilder, "thirdsBlock")

      // Check for specific lines generated by WordBox for "black", "red", and "1st 12"
      // This ensures the WordBox content is correctly integrated into the side blocks
      sideResult should include(WordBox.wordBox("black")(1)) // e.g., "| b |"
      sideResult should include(WordBox.wordBox("red")(1))   // e.g., "| r |"
      thirdsResult should include(WordBox.wordBox("1st 12")(1)) // e.g., "| 1 |"
    }

    "build a complete table string" in {
      val finalResult = new TableBuilder(totalWidth, height, Some(5))
        .buildHexPart()
        .buildTableGridPart()
        .buildSideParts()
        .getResult
      finalResult.linesIterator.length should be > 10
      finalResult should include("5")
      // Check for specific lines generated by WordBox for "black" and "1st 12"
      finalResult should include(WordBox.wordBox("black")(1)) // e.g., "| b |"
      finalResult should include(WordBox.wordBox("1st 12")(1)) // e.g., "| 1 |"
    }
  }
}