name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history to avoid missing files
          submodules: recursive  # Clone submodules if any

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'

      - name: Set up sbt
        uses: sbt/setup-sbt@v1

      - name: install dependancies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libxtst6 libxrender

      - name: Verify coverage file exists
        run: |
          ls -R target | grep scoverage || true

      - name: Run tests and Submit to Coveralls
        run: xvfb-run sbt clean coverage test coverageAggregate coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
